baseurl = "http://drone.ru/"
languageCode = "ru"
theme = "drone"
title = "Андрей Павленко"

[indexes]
  tag = "tags" #TODO

[params]
  themeColor = "theme-base-08"
  layoutReverse = true
  description = "Changelog в картинках"
  googleAnalytics = "UA-96759973-1"
  disqusShortname = "droneru"
  author = "Andrey Pavlenko"
